version: 2

project_name: relay-server

before:
    hooks:
        - go mod tidy

builds:
    - main: ./cmd/server/main.go
      goos:
          - linux
          - windows
      goarch:
          - amd64
          - arm64
      ldflags:
          - -s -w
          - -X relay-server/internal/handlers.Version={{.Version}}
          - -X relay-server/internal/handlers.BuildTime={{.Date}}
          - -X relay-server/internal/handlers.GitCommit={{.FullCommit}}

archives:
    - formats: ["zip"]
      name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
    github:
        owner: "RelayCore"
        name: "relay-server"
