version: "3.8"

services:
    relay-server:
        build: .
        restart: unless-stopped
        environment:
            - PORT=36954
        volumes:
            - ./uploads:/app/uploads
            - ./data:/app/data
            - ./config.yaml:/app/config.yaml
        expose:
            - "36954"

    imageproxy:
        image: ghcr.io/willnorris/imageproxy
        restart: unless-stopped
        command:
            - -addr=0.0.0.0:8080
            - -cache=/cache
            - -passRequestHeaders=Cookie
        volumes:
            - ./imageproxy-cache:/cache
        ports:
            - "8080:8080"

    certbot:
        image: certbot/certbot
        profiles: ["letsencrypt"]
        volumes:
            - ./certs:/etc/letsencrypt
            - ./nginx/www:/var/www/certbot
        entrypoint: /bin/sh -c
        command: >
            "trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot; done"

    nginx:
        image: nginx:1.29-alpine
        depends_on:
            - relay-server
        ports:
            - "36954:36954"
        profiles: ["local"]
        volumes:
            - ./nginx/nginx.conf.local.template:/etc/nginx/nginx.conf:ro
        entrypoint: nginx -g "daemon off;"

    nginx-letsencrypt:
        image: nginx:1.29-alpine
        depends_on:
            - relay-server
        profiles: ["letsencrypt"]
        ports:
            - "36954:36954"
        environment:
            - DOMAIN
        volumes:
            - ./nginx/nginx.conf.letsencrypt.template:/etc/nginx/nginx.conf:ro
            - ./certs:/etc/letsencrypt:ro
            - ./nginx/www:/var/www/certbot
        entrypoint: nginx -g "daemon off;"

    nginx-selfsigned:
        image: nginx:1.29-alpine
        depends_on:
            - relay-server
        profiles: ["selfsigned"]
        ports:
            - "36954:36954"
        environment:
            - DOMAIN
        volumes:
            - ./nginx/nginx.conf.selfsigned.template:/etc/nginx/nginx.conf:ro
            - ./nginx/selfsigned:/etc/nginx/selfsigned:ro
        entrypoint: nginx -g "daemon off;"
